New UI for HomePage
ucsb-cs184-f24/team04-GOLDTracker pull request #96
Opened 2024-12-05 12:55 UTC by xinyao-song

Added a new scroll and UI for home

2024-12-05 18:24 UTC, AllenHsm approved these changes
Perfect! The search bar disappear when scrolling down!

2024-12-05 18:34 UTC, AllenHsm requested changes
Need to correct several error causing it unable to search subject areas like "CHIN" and the wrong department list.

2024-12-05 18:34 UTC, AllenHsm commented on GOLDTracker/src/components/SearchComponent.js
> +import departmentMapping from "../assets/departmentMapping.json";
should replace departmentMapping with departmentList.json

2024-12-05 18:34 UTC, AllenHsm commented on GOLDTracker/src/components/SearchComponent.js
> +      const apiUrl = /^[A-Z]{2,}\s[\dA-Z]+$/.test(searchTerm)
For subject area search and department search, we should use two different parameters in API. You can see the difference in current main branch. 

      if (deptCode){
        apiUrl = /^[A-Z|a-z]{2,}\s[\d(A-Z|a-z]+$/.test(searchTerm)

        ? `${API_URL}?quarter=${quarter}&courseId=${encodeURIComponent(
            searchTerm
          )}&includeClassSections=true`
        : `${API_URL}?quarter=${quarter}&deptCode=${encodeURIComponent(
            searchTerm
          )}&includeClassSections=true&pageNumber=1&pageSize=30`;
      }
      else{
        apiUrl = /^[A-Z|a-z]{2,}\s[\d(A-Z|a-z]+$/.test(searchTerm)
        ? `${API_URL}?quarter=${quarter}&courseId=${encodeURIComponent(
            searchTerm
          )}&includeClassSections=true`
        : `${API_URL}?quarter=${quarter}&subjectCode=${encodeURIComponent(
            searchTerm
          )}&includeClassSections=true&pageNumber=1&pageSize=30`;
      }

2024-12-05 18:34 UTC, AllenHsm commented on GOLDTracker/src/components/SearchComponent.js
> +      label: departmentMapping[code][0],
remove the [0] here to fit the new mapping json. Should be: label: departmentMapping[code]

2024-12-06 01:14 UTC, AllenHsm approved these changes
LGTM!!!

2024-12-06 01:34 UTC, Simonmann17 approved these changes
LGTM!

2024-12-06 01:50 UTC, merged